version: '3.7'

services:
  nginx:
    image: nginx:1.21.1
    ports:
      - '8080:80'
    volumes:
      - ./etc/nginx/conf.d/backend.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/cartostory
  backend:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - NODE_JWT_SECRET=${NODE_JWT_SECRET}
  mailer:
    environment:
      - MAILER_SIGN_UP_QUEUE=${MAILER_SIGN_UP_QUEUE}
      - MAILER_SIGN_UP_EXCHANGE=${MAILER_SIGN_UP_EXCHANGE}
      - MAILER_MANDRILL_API_KEY=${MAILER_MANDRILL_API_KEY}
      - AMQP_HOST=${AMQP_HOST}
      - AMQP_PORT=${AMQP_PORT}
      - NODE_ENV=${NODE_ENV}
  database:
    image: kartoza/postgis:13.0
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS}
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.12.4-management-alpine
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
