version: '3.7'

volumes:
  database-data-test:

services:
  backend:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - database
      - flyway
      - rabbitmq
    command: >
      sh -c "cd /app && npm run test"
  mailer:
    build:
      context: ../mailer
      target: development
    restart: always
    volumes:
      - ../mailer:/app
      - /app/node_modules
  database:
    volumes:
      - database-data-test:${PGDATA}
