version: '3.7'

volumes:
    database-data-dev:

services:
  backend:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
    depends_on:
      - database
      - flyway
      - rabbitmq
    command: >
      sh -c "cd /app && npm run dev"
  mailer:
    build:
      context: ../mailer
      target: development
    volumes:
      - ../mailer:/app
  database:
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - database-data-dev:${PGDATA}
