version: '3.7'

volumes:
    database-data-dev:

services:
  backend:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
    depends_on:
      - database
      - flyway
    command: >
      sh -c "cd /app && npm run dev"
  database:
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - database-data-dev:${PGDATA}
