name: Cartostory CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd packages/docker
          cp .env.example .env
          cd ..
          make run-test
